{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "aws-spot-price-exporter.fullname" . }}
  labels:
    {{- include "aws-spot-price-exporter.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ default .Values.serviceMonitor.namespace .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aws-spot-price-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
      scheme: http


{{- end }}